

###################################
#####   RANCHER  MONITORING   #####
###################################


rancher-monitoring:
  grafana:
    adminPassword: admin

    labels:
      app: grafana
    podLabels:
      app: grafana
    service:
      labels:
        app: grafana

    sidecar:
      dashboards:
        # searchNamespace: cattle-dashboards
        searchNamespace: ALL
        folder: /tmp/dashboards

    additionalDataSources:
    - name: Loki
      type: loki
      url: http://rancher-monitoring-loki:3100
      isDefault: false




###################################
########       LOKI       #########
###################################


loki:
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  # Set Loki log retention to 29days
  config:
    chunk_store_config:
      max_look_back_period: 696h
    table_manager:
      retention_deletes_enabled: true
      retention_period: 696h

  #persistence:
  #  enabled: true
  #  accessModes:
  #  - ReadWriteOnce
  #  size: 10Gi
  #  storageClassName: "delete-without-pvc"                     # <-- Update with your storageclass




#####################################
########      PROMTAIL      #########
#####################################


promtail:
  config:
    lokiAddress: http://rancher-monitoring-loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - docker: {}
        # - cri: {}

  rbac:
    create: true
    pspEnabled: true

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi


  defaultVolumes:
  - name: docker
    hostPath:
      path: /var/logs/containers
  - name: pods
    hostPath:
      path: /var/log/pods

  defaultVolumeMounts:
  - name: docker
    mountPath: /var/logs/containers
    readOnly: true
  - name: pods
    mountPath: /var/log/pods
    readOnly: true

  # Add Promtail to masters even if installed with rancher
  # tolerations:
  # - operator: "Exists"

