kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."host.docker.internal:5000"]
    endpoint = ["http://host.docker.internal:5000"]
nodes:
- role: control-plane
# - role: worker
#   extraMounts:
#   - hostPath: ./data
#     containerPath: /data
- role: worker
  extraMounts:
  - hostPath: ./data
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: ./data
    containerPath: /var/local-path-provisioner
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
  - containerPort: 30001
    hostPort: 30001
  - containerPort: 30002
    hostPort: 30002
  - containerPort: 30003
    hostPort: 30003
  - containerPort: 30004
    hostPort: 30004
  - containerPort: 30005
    hostPort: 30005
  - containerPort: 30006
    hostPort: 30006
  - containerPort: 30007
    hostPort: 30007
  - containerPort: 30008
    hostPort: 30008
  - containerPort: 30009
    hostPort: 30009
  - containerPort: 30010
    hostPort: 30010
  - containerPort: 30080
    hostPort: 30080
  - containerPort: 30443
    hostPort: 30443





