apiVersion: v1
kind: Service
metadata:
  name: linkerd-viz-nodeport
  namespace: linkerd-viz
  labels:
    component: web
spec:
  type: NodePort
  selector:
    component: web
  ports:
  - name: ui
    nodePort: 30000
    port: 8084
    protocol: TCP
    targetPort: 8084
  # - name: prometheus
  #   nodePort: 30001
  #   port: 9994
  #   protocol: TCP
  #   targetPort: 9994
